### ISSUE TITLE
Multiple GUI improvements

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#100]
I'm just going to list these and separate issues can be made if need be, and I'll just update this issue with more suggestions for now.

- [x]  In the 'expanded' row view, the short name should be listed again and made a link. The row above is visually 'detached' from the expanded region - it's hard to tell if it goes with the expanded view above, or below it, and the "up arrow" adds to the cognitive load to navigate, as does the fact that the title of the experiment in the expansion is larger than the text in the original row. Open to suggestions overall.
- [x] Show the curation status in the administrator's view. Pretty much all the information available [here](https://gemma.msl.ubc.ca/expressionExperiment/showAllExpressionExperiments.html) should be  in the new browser as well.
- [x] Abbreviate the Description in the row expansion (some are very long), make it look tidier. e.g. 150 words or something.

**Comment by oganm** [comment]
Do you think removing the bottom shadow is good for better specifying that the details belong to the row above?

No bottom shadow
![image](https://github.com/PavlidisLab/GemBrow/assets/6352379/a24502ae-0608-4ed0-a7b5-37d161c7b011)

Double shadow (current version)
![image](https://github.com/PavlidisLab/GemBrow/assets/6352379/c5cca53a-5655-42a0-8b7d-a693e25fdd5f)

**Comment by oganm** [comment]
Another particularly annoying thing is the widths of elements changing between expanded and non-expanded views causing rows to shift on click. 

![image](https://github.com/PavlidisLab/GemBrow/assets/6352379/1c489f2f-7c3f-4bb2-9f6a-060d490478f2)

see the difference in position between the expanded and shrunk version. Still trying to figure out what causes the difference

**Comment by ppavlidis** [comment]
Shadow: seems a bit of a tossup to me but I've spent too much time looking at it so might not have the right perspective.

And yes, the shifting of the rows is something I wanted to mention as well, forgot.

**Comment by oganm** [comment]
Shifting rows is fixed in f488281cfbef38fa1496500c281bfbdc691225c6

**Comment by oganm** [comment]
Second point is #75

**Comment by arteymix** [comment]
Regarding curation status, I believe we expose it regardless of the user privileges. I will change this in the API to require at least `GROUP_ADMIN`.
