### ISSUE TITLE
Filter datasets by platform type (RNA-Seq v.s. microarray)

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#15]
- [x] add two custom cases of technology types for microarray and RNA-Seq 
- [x] for the microarray tech type, generate a sub-clause for one color two colors and dual mode
- [x] hide generic gene list platforms as this should be done through the custom RNA-Seq case
- [x] use original platform for filtering only if a sequencing platform is picked 
- [x] when filtering by a specific sequencing platform, add a clause to ensure that at least one sample has a gene list technology type as current platform

**Comment by arteymix** [comment]
We can filter platforms by technology type, but not yet select all the platforms from a given tech type.

**Comment by libby-natola** [comment]
Started reformatting platformSelector. Commited in 659a943c7fe71ce55270d554699d49f15531997f. 

Allow multiple selection in Platforms browser, add select all buttons to technology types, emit selectedPlatforms when platformSelector window is closed. Changed 'platform' to 'platforms' in many variable names across multiple components.

**Comment by libby-natola** [comment]
More reformatting to platformSelector. Committed in 068b20630b7d3f83b1b6b0666fa5a1ccf980c464. 

Remove checkboxes and buttons, when a technology type is selected select all platforms of that technology, if all platforms selected, only display the technology type in the platformSelector, not every individual platform.

**Comment by arteymix** [comment]
As we stated in the lab meeting, a RNA-Seq dataset has samples with a generic platform and a sequencing original platform.

We can use the same workaround @oganm suggested for annotations: add a clause for at least one genelist platform and another clause for at least one sequencing original platform. It will not guarantee that at least one sample has both, but it should be equivalent in practice with the datasets we have.
