### ISSUE TITLE
Incorrect counts for free text terms

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#26]
The term "154 CAG Repeat Mutation" is displayed as having >1600 occurrences which is wrong.

![image](https://github.com/PavlidisLab/GemBrow/assets/206415/eab575a3-14ac-49c7-922a-1891b33bc3db)

When you click on it, it shows the (most likely) correct value of 1.

![image](https://github.com/PavlidisLab/GemBrow/assets/206415/fe7fc61d-d5dd-4379-9a11-99e74486bc5b)

**Comment by arteymix** [comment]
This sounds like a backend quirk where free text terms are aggregated together.

**Comment by arteymix** [comment]
It's fixed, I was accidently aggregating twice by VALUE_URI which is null for free-text terms.
