### ISSUE TITLE
Updates to download button

### ISSUE THREAD

**Issue by libby-natola** [PavlidisLab/GemBrow#30]
The downloaded file includes some data unnecessary for the user and lacks some necessary information. Remove the columns 'id', 'score', and 'highlights'. Add a header to the file with the publication citation and the user's filter and query. Add a local time-date stamp to the filename.

**Comment by arteymix** [comment]
I'll provide you the license excerpt. Ideally that should be configurable as we intend to standardize how data is licensed in Gemma very soon.
