### ISSUE TITLE
Sort queried datatable

### ISSUE THREAD

**Issue by libby-natola** [PavlidisLab/GemBrow#32]
If you enter a query, the data table sorts automatically by score, and then experiments with the same score are sorted arbitrarily. We may want to add a subsequent variable to sort data with equal scores or allow users to specify this. Although, as it looks like the score column is hidden from the user it may not clarify for them how experiments are ordered in the data table.

**Comment by arteymix** [comment]
The backend now sorts by score then ID. There's no support for sorting search results by an arbitrary field and it will be too complicated to achieve unfortunately in the upcoming release. I suggest that we keep it as it is with the sorting disabled when a search results are displayed.

**Comment by arteymix** [comment]
Datasets of equal scores are now sorted by the selected sorting order. It would be good in the future to allow users to sort by multiple columns.

**Comment by arteymix** [comment]
Datasets of equal scores are now sorted by the selected sorting order. It would be good in the future to allow users to sort by multiple columns.
