### ISSUE TITLE
When no data is available in the platform selector, hide the splitter

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#34]
It's a small cosmetic fix.

![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/66af7c64-4957-41e1-a071-19435ea82eca)

**Comment by libby-natola** [comment]
Divider line is now conditional on selectablePlatforms.length being > 0.

**Comment by libby-natola** [comment]
Fixed in 69d62466c3f1e9644b02897dd8af396844bf2d5e
