### ISSUE TITLE
CodeSnippet v-menu positioning error

### ISSUE THREAD

**Issue by libby-natola** [PavlidisLab/GemBrow#39]
The v-menu for CodeSnippets repositions when it is opened, but not when a different tab is selected. Because v-cards within tabs are different sizes, v-cards that are longer than the initially selected tab run off the window and shorter v-cards are in the middle of the screen, far from the menu button. 

@arteymix came up with a workaround to adjust menu position based on card size, but I have raised an issue on vuetify's github page.

**Comment by oganm** [comment]
This behaviour seems to have been fixed
