### ISSUE TITLE
Selecting "RNA-Seq" and a specific microarray platform returns no results

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#48]
![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/92c121e0-cc25-44b3-bd32-5f141abe389d)

**Comment by arteymix** [comment]
@libby-natola for this one, you have to look at how the filter is generated. I think there's a conflict when you combine a RNA-Seq clause (original platform is sequencing AND current platform is genelist) and individual microarray platforms. The "original platform is sequencing" part should not appear in that case.

**Comment by libby-natola** [comment]
commit d878499282599304516b07bb5aefc0b5729ffa7b
