### ISSUE TITLE
Progress bar for the annotation selector is not active when individual categories are loading

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#53]
This is due to how we bind the progress bar state to the state in the store. We need to do some kind of disjunction of the pending state of all the queries involved.

To track individual pending state, we have to manually handle the `getDatasetsAnnotationsByCategory` endpoint in the store. Relevant documentation: https://christianmalek.github.io/vuex-rest-api/api.html

 - [ ] track the pending state of individual annotation query in the store (i.e. under `pending.datasetsAnnotationsByCategory.{categoryId}`)
 - [ ] redefine `loadingAnnotation` in the browser component to account for all involved API requests

**Comment by libby-natola** [comment]
commit a89cffa6f4c0a30beaffc0e502572316cb55ae7a
