### ISSUE TITLE
Translate highlights object paths into understandable labels

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#54]
The exhaustive list of paths is in:

https://github.com/PavlidisLab/Gemma/blob/9ccaee39423c78cbb45e6b86fc8a164ac220cdf9/gemma-core/src/main/java/ubic/gemma/core/search/source/HibernateSearchSource.java#L47C1-L60

**Comment by libby-natola** [comment]
commit fedcc64b3942cf4dde02d4f3ec0770b1dcd4b2c3
