### ISSUE TITLE
Use colors from the material palette for coloring term chips

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#66]
There are colors that are very close to those used by Gemma.

I can adjust the colors used by Gemma to be consistent with that of GemBrow for the next patch release.

Reference: https://v2.vuetifyjs.com/en/styles/colors/#material-colors

**Comment by libby-natola** [comment]
commit d2e0a3b32b6ad78168ecd0bfa3b1473722c58a75 I used "yellow lighten-3", "green lighten-3", and "blue lighten-3" for factor value, experiment tag, and biomaterial, respectively
