### ISSUE TITLE
(Minor) Search field should prompt user to indicate they just need to start typing

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#73]
Perhaps instead of being blank, the search field should by default have greyed-out text reading "Type a query"

**Comment by libby-natola** [comment]
By this, do you mean you want to replace the "Search" Text in the query bar in the upper left with "Type a query"? Or do you want it to say "Search" when the page first opens and change to "Type a query" in the bar when the user clicks on it?

**Comment by ppavlidis** [comment]
OK my mistake, it was looking blank to me but I forgot that when it first loads is says 'search'.
