### ISSUE TITLE
Replace GitHub with Bioconductor in the code snippet for gemma.R once the release is published

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#77]
We currently have to request users to use gemma.R from GitHub since the current published version on Bioconductor lacks some functionalities for searching and filtering datasets.

@oganm let us know when it's ready!

**Comment by arteymix** [comment]
@oganm has this been resolved in gemma.R 2.0.0?

**Comment by oganm** [comment]
In 3.0 bioconductor release, all filter functionalities will be included. Release date is May 1st

**Comment by oganm** [comment]
Closed by 556e4706961c98fd5daceea86accf857884ef185
