### ISSUE TITLE
Provide a header to explain the meaning of the numbers in the navigation area (Minor)

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#87]
The numbers could be confusing, so I suggest we put in something like "# of Experiments" in this area, above the values, to the right of "Taxa". 

This should provide a stronger cue for the whole navigation area, no need to add this to each "heading".

<img width="382" alt="image" src="https://github.com/PavlidisLab/GemBrow/assets/206415/d0bcea14-9dd8-47a4-880c-418822166b4a">

**Comment by arteymix** [comment]
At this time, only annotations are inaccurate due to the lack of accounting for inference.

Platforms, technology types and taxa should be exact or very close by, at least until the corresponding denormalized tables in Gemma are synced.

**Comment by arteymix** [comment]
![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/7c8c9692-5607-45b6-a29e-6048dfaa5f12)

That should make it clear.

**Comment by arteymix** [comment]
And in the help section:

![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/47fdbc13-2ab7-45a7-b6a1-2c6416df3955)
