### ISSUE TITLE
Information on matching strings takes up too much space.

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#91]
Example: https://gemma.msl.ubc.ca/browse/#/q/%22FACS-sorted%20microglia%22

<img width="1187" alt="image" src="https://github.com/PavlidisLab/GemBrow/assets/206415/5bd5631a-588e-426c-8a5b-1efacd32f4c1">

Each experiment should be more compact by default. The information on which strings matched should be limited to just one? Having five lines of this plus the experiment title means you have to scroll a lot just to see one page of results. Ideally, a single page of results would fit on the page without scrolling. It's hard to read and grasp what you have, and the text describing the matches is really long.

Not logged in.

**Comment by ppavlidis** [comment]
One solution is to put the highlighting text (or at least most of it) in the row-expanded view only, but we should try to make it more compact anyway. Transforming "Tagged ... text" prefix into something briefer would help (maybe we can omit that entirely, though for debugging it can be useful), as well as showing less highlighted text?

**Comment by arteymix** [comment]
I've removed all highlight listings from the production build. Instead, we simply highlight the relevant component parts. 

I think we would also want to highlight annotations this way.
