### ISSUE TITLE
Checking a microarray platform unchecks RNA-Seq

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#94]
First:

![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/b79cbea0-fb36-4e04-82ea-166ffa2164ea)

Then:

![image](https://github.com/PavlidisLab/GemBrow/assets/1318477/b4d22c30-b541-4f64-92b5-9c5d2d7d11ba)

**Comment by oganm** [comment]
checking any sub-option causes any checked main option to be unchecked. (for debug mode picking specific rna-seq,microarray or "other" options will cause any other option to be unchecked)
